apiVersion: v1
kind: Secret
metadata:
  name: 16063682-testsvcacnt-pull-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6Ik1UWXdOak0yT0RKOGRHVnpkSE4yWTJGamJuUTZaWGxLYUdKSFkybFBhVXBUVlhwVmVFMXBTamt1WlhsS2VtUlhTV2xQYVVrd1RsUnNhVmt5VlhoT1IxazBXbTFaTUUxRVNYZFBSR2N6VFRKYWJVNUVUVEpQVjFVeVRXcG5kMXBUU2prdWJIVmFlbFZ1VVdFNVdHeGFjMFJwZEROQ1ZISmFZMnd0VFVFNE1uZFJVMmRNT0hneFIxSlFaRUpvTTJvd2RtZGlRMlpuWVZOVlEzZHVTa3h3VVdZNE0yRndkR2Q1UkZwTFZYWktiVWxzTm5wNmVYTjVkV2hXY1hjM0xUUjNYeTFLVVdwTFJsRnJaRTl4VWtGVlFtbHhhSFJTTFRSMVVEZENVRkJpUzAxSGVrRTRUSEJQYmkxNFdIRkhOWFIwV25WcmJsVlpTbmRqUTNKNGRsRmxiVEJPWWpaTFNqWTVTemxPV205bFV6VXhjbE5aWmtkUGNFVlhaRFJ2VW5kcFdreHlZamM0Y1Y5alIybDNRVU5aTjFOaVgwSjNTSEJRWTBONmIwbzBTSGcwVm1WVVJXTm9iVmRoUVZWSFFXOTZTWE5MYUhWalozWjBVR2t3T1ZFdFJUUlBiMmxVVG1wNlJFRnFiMFJuZEhCbVRYbDBaa2hUTlVkTlVreERWVkpyU2twSU5tdFFXa1JQVjBOemFGVnVSVGxUVjNkeGNucE1ZVVJEVVdOMWRFZHVUMjVEWDJ4U1Nqa3dhblpxZW5oNlFXWlBhM1JvYjJ0Q04zQkdRWGRvUjAxQ04waDRkbTVHUkVnNVExbDJjRUpxYUVGNGFEUnNhM1kwU0hKWVJHRklYMVJoY2tKMWRtRlhOalZWZDJoRmNFUmxVVEZNVGtjNVNXRlhWbFI1VkU1RlpreFVjM2RETmxrNGFUZHlZbmR0YWtRNGFWTlNUMTkxTlVkYVdubHViRGwzV0VsUmRYUjZOME4yWW05NVpIUXlhV1IyY0hOaldubHhNM1ZPU0VWd2FYUkZSblJEV2xGakxYZERSMWxrWVRNeVdWaHRTV3hHUkRsRmNIUmhVRGh5YkZOMGMzTkhSMnRMUW1SSFJYcERSbUpRYzFoRVJ6TkJiVEJRYm1GMlQxQk5WRmRrTldWTlMxYzJSRGx5ZERWUFRFcHJSV0ZWUkVwUlJrUm5NbFYzVFc4M09GUnVXRTFVUmxSQ1NVRkhUa3BHZEhkV1JDMTJaMVJ6YkhReGFqQkpVekF3VEhKMVowOWFhSFpzUjJkaExWUXRiR1JJWjNrMldXSkdNMDl1UkVSVU9XODNlRlJvVTBKZmVubFFVMDE1T0dWSmFVTmllVTlrYm5kTU4yVlhiVmgwY25CUGFEUm1ibXRuTWtFPSJ9fX0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-ss
spec:
  selector:
    matchLabels:
      msvc: redis
  serviceName: redis-svc
  replicas: 3
  template:
    metadata:
      labels:
        msvc: redis
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: msvc
                operator: In
                values:
                - redis
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: registry.redhat.io/rhscl/redis-6-rhel7
        imagePullPolicy: IfNotPresent
        ports:
        - name: redisport
          containerPort: 6379
          protocol: TCP
        # volumeMounts:
        # - name: redis-pvc
        #   mountPath: /var/lib/redis/data
        securityContext: 
          runAsUser: 1001
          allowPrivilegeEscalation: true
        env:
        - name: REDIS_PASSWORD
          value: rgpass
      imagePullSecrets:
       - name: 16063682-testsvcacnt-pull-secret
  # volumeClaimTemplates:
  # - metadata:
  #     name: redis-pvc
  #   spec:
  #     accessModes: [ "ReadWriteMany" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    msvc: redis
  ports:
  - port: 6379
    targetPort: 6379

