
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: udp-listener
    app.kubernetes.io/component: udp-listener
    app.kubernetes.io/instance: udp-listener
  name: udp-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: udp-listener
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: udp-listener
    spec:
      containers:
      - image: docker.io/mendhak/udp-listener
        name: udp-listener
        ports:
        - containerPort: 5005
          protocol: UDP
          name: udp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: udp-listener
    app.kubernetes.io/component: udp-listener
    app.kubernetes.io/instance: udp-listener
  name: udp-listener
spec:
  ports:
  - name: 5005-udp
    port: 5005
    protocol: UDP
    targetPort: 5005
  selector:
    deployment: udp-listener
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: udp-listener
    app.kubernetes.io/component: udp-listener
    app.kubernetes.io/instance: udp-listener
  name: udp-listener
spec:
  port:
    targetPort: 5005-udp
  to:
    kind: ""
    name: udp-listener
