apiVersion: v1
data:
  MYSQL_DATABASE: c2FtcGxlZGI=
  MYSQL_PASSWORD: cmdwYXNz
  MYSQL_ROOT_PASSWORD: cnRwYXNz
  MYSQL_USER: cmFnaHU=
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: samplemysqlapp
    app.kubernetes.io/component: samplemysqlapp
    app.kubernetes.io/instance: samplemysqlapp
  name: samplemysqlsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: samplemysqlapp
    app.kubernetes.io/component: samplemysqlapp
    app.kubernetes.io/instance: samplemysqlapp
  name: samplemysqlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: samplemysqlapp
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: samplemysqlapp
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: samplemysqlsecret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: samplemysqlsecret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: samplemysqlsecret
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7
        name: samplemysqlapp
        ports:
        - containerPort: 3306
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: samplemysqlapp
    app.kubernetes.io/component: samplemysqlapp
    app.kubernetes.io/instance: samplemysqlapp
  name: samplemysqlapp
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: samplemysqlapp